version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8181:8080
    networks:
      - internal

volumes:
  postgres-data:
    driver: local

networks:
  internal:
    driver: bridge

