app:
  secret: cfcd208495d565ef66e7dff9f98764da
server:
  trusted_subnet: "127.0.0.0/24"
  enable_https: false
  addr: "127.0.0.1:8080"
  base_url: "http://localhost:8080"
storage:
  type: memory
short_url:
  ttl: 360
